
#---------------------------------------------
# fonts
font_family      JetBrainsMono Nerd Font

bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.0

active_tab_font_style   bold-italic
inactive_tab_font_style normal


#---------------------------------------------
# scrolling 

scrollback_lines 5000
scrollbar always
scrollbar_interactive yes
scrollbar_jump_on_click yes
scrollbar_width 0.5
scrollbar_hover_width 1.25
scrollbar_hitbox_expansion 0.5


#---------------------------------------------
# url handling 
detect_urls yes
show_hyperlink_targets yes
underline_hyperlinks always


#---------------------------------------------
# layout 
remember_window_size  yes
initial_window_width 100c
initial_window_height 33c
enabled_layouts splits:split_axis=auto, tall:bias=70;full_size=1;mirrored=false, stack

window_border_width 1pt
draw_minimal_borders yes
hide_window_decorations no


#---------------------------------------------
# tabs
tab_bar_edge top
tab_bar_align left
tab_bar_min_tabs 2

tab_bar_margin_height 0.0 0.0
tab_bar_style powerline
tab_powerline_style round
tab_activity_symbol "  "

tab_title_template "{activity_symbol}{fmt.fg.tab}{sup.index} {title} [{num_windows}] {tab.last_focused_progress_percent}"
active_tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{sup.index} {title} [{num_windows}] {tab.progress_percent}"

